### ISSUE TITLE
Build artifact?

### ISSUE THREAD

**Issue by Fdawgs** [blindpandas/unrtf-win32#1]
Hi @blindpandas @mush42, did you ever manage to get a working artifact out of this?

**Comment by mush42** [comment]
Hi @Fdawgs 

Unfortunately, I failed to build this. I resorted to [pandoc](https://github.com/jgm/pandoc) as a well-maintained alternative.

**Comment by Fdawgs** [comment]
Great, thanks @mush42, never heard of Pandoc before!
